// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdYQKRL2onznAZaHPhMvO5uRxb2kyuOfY',
    appId: '1:630647758640:web:3373a4392348d44931f2f5',
    messagingSenderId: '630647758640',
    projectId: 'tatendria',
    authDomain: 'tatendria.firebaseapp.com',
    storageBucket: 'tatendria.firebasestorage.app',
    measurementId: 'G-76WKJ9RE36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEjAVgCi34HmdEOh4hikIelQEhFP-BHyI',
    appId: '1:630647758640:android:8d46d4cdd001d24631f2f5',
    messagingSenderId: '630647758640',
    projectId: 'tatendria',
    storageBucket: 'tatendria.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIleJY5i6H_uw3XAtjt2zJtNeH1OVD8uw',
    appId: '1:630647758640:ios:510aabe82d67f2ac31f2f5',
    messagingSenderId: '630647758640',
    projectId: 'tatendria',
    storageBucket: 'tatendria.firebasestorage.app',
    iosBundleId: 'dev.binteconsulting.tendria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIleJY5i6H_uw3XAtjt2zJtNeH1OVD8uw',
    appId: '1:630647758640:ios:9985eab4666b1b8e31f2f5',
    messagingSenderId: '630647758640',
    projectId: 'tatendria',
    storageBucket: 'tatendria.firebasestorage.app',
    iosBundleId: 'com.example.tendria',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdYQKRL2onznAZaHPhMvO5uRxb2kyuOfY',
    appId: '1:630647758640:web:2fd74e581e359f9131f2f5',
    messagingSenderId: '630647758640',
    projectId: 'tatendria',
    authDomain: 'tatendria.firebaseapp.com',
    storageBucket: 'tatendria.firebasestorage.app',
    measurementId: 'G-9GD0VE76ET',
  );
}
